### ISSUE TITLE
Model Testing

### ISSUE THREAD

**Issue by GemmaTuron** [ersilia-os/eos4cxk#3]
Hi, 
This model is ready for testing! Please confirm it works on Colab and CLI.

Thanks

**Comment by carcablop** [comment]
Hello. 
This model ran successfully on the CLI and Google Colab (fetch, serve and predict with "eml_canonical.csv" as input).
Fetch log:  
[log_fetch_eos4cxk.txt](https://github.com/ersilia-os/eos4cxk/files/10788458/log_fetch_eos4cxk.txt)
Link to google colab: https://colab.research.google.com/drive/1UVDV2O9JtEuu9C3l0a01K-xZlVXmBZ2l

This is the output of the model: 
[ouput_cli_eos4cxk.csv](https://github.com/ersilia-os/eos4cxk/files/10788438/ouput_cli_eos4cxk.csv)

This is the output with one molecule as input: 
[output_predict_onemole_eos4cxk.txt](https://github.com/ersilia-os/eos4cxk/files/10788471/output_predict_onemole_eos4cxk.txt)

**Comment by Femme-js** [comment]
Hi @GemmaTuron !

This model ran successfully on google colab.
https://colab.research.google.com/drive/1O8dQ7-sdSZii6WehgasRwCzRDLYqInum

On my CLI, I am getting the following error. The issue seems to be related to the docker image. Do I need to download any specific docker image for this model to run successfully?

[eos4cx1k.log](https://github.com/ersilia-os/eos4cxk/files/10838301/eos4cx1k.log)

**Comment by GemmaTuron** [comment]
Hi @Femme-js,

Just to confirm I've also tried fetching the model in my CLI with success. The Docker images are there by default because we are in process of transitioning to Docker, but we haven't yet so you should not run into issues there.
Have you pulled the latest version of Ersilia's code?

**Comment by Femme-js** [comment]
Hello @GemmaTuron 

I have pulled the latest changes from ersilia. And it shows the same error still. 

[eos4cxk3.log](https://github.com/ersilia-os/eos4cxk/files/10847721/eos4cxk3.log)

**Comment by GemmaTuron** [comment]
Hello @Femme-js 

Could it be you are running Ersilia from the code you modified in PR https://github.com/ersilia-os/ersilia/pull/606 ?
It gives the list out of range error, same as the PR test

**Comment by GemmaTuron** [comment]
I'll close this as the model is working, just tested in my system
