### ISSUE TITLE
Clean UP & Dockerization eos4cxk

### ISSUE THREAD

**Issue by GemmaTuron** [ersilia-os/eos4cxk#5]

**Comment by emmakodes** [comment]
Hello @GemmaTuron before I start refactoring this model, I ran prediction for `C1=C(SC(=N1)SC2=NN=C(S2)N)[N+](=O)[O-]` smile and I get the following output:
```
{
    "input": {
        "key": "NQQBNZBOOHHVQP-UHFFFAOYSA-N",
        "input": "C1=C(SC(=N1)SC2=NN=C(S2)N)[N+](=O)[O-]",
        "text": "C1=C(SC(=N1)SC2=NN=C(S2)N)[N+](=O)[O-]"
    },
    "output": {
        "outcome": [
            0.0,
            0.0,
            0.0,
            0.0,
            0.0,
            0.0,
            0.0,
            0.0,
            0.0,
            0.0,
            1.0,
            1.0,
            0.0
        ]
    }
}
```
See the outcome above, I guess the predictions are meant to be in 0s and 1s in a list right?  Just to be clear

**Comment by emmakodes** [comment]
Okay, they are since the output shape of the model is a List and the Output specified for the model is Boolean(either 0 or 1)

**Comment by GemmaTuron** [comment]
I think that works fine @emmakodes !

**Comment by emmakodes** [comment]
Hello @GemmaTuron I made a PR
